import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import type Database from 'better-sqlite3-multiple-ciphers'
import { termsFor } from './i18n'
import { embedImageFile, savePdf } from './helpers'
import type { Subsystem } from '@shared/types'

const BRAND = rgb(0.08, 0.52, 0.34)
const INK = rgb(0.11, 0.16, 0.23)
const MUTED = rgb(0.45, 0.5, 0.58)
const LINE = rgb(0.82, 0.85, 0.88)

const METHOD_LABEL: Record<string, string> = {
  momo: 'MTN Mobile Money',
  orange: 'Orange Money',
  other: 'Other'
}

/** Generates a localized A5 payment receipt for a single fee payment. */
export async function generateReceipt(db: Database.Database, paymentId: number): Promise<string> {
  const payment = db
    .prepare(
      `SELECT p.*, s.first_name, s.last_name, s.admission_no, c.name as class_name, c.subsystem, s.class_id, s.id as student_id
       FROM fee_payments p JOIN students s ON s.id = p.student_id
       JOIN classes c ON c.id = s.class_id WHERE p.id = ?`
    )
    .get(paymentId) as any
  if (!payment) throw new Error('Payment not found.')
  const school = db.prepare('SELECT * FROM schools WHERE id = 1').get() as any
  const subsystem: Subsystem = payment.subsystem
  const T = termsFor(subsystem)

  // Balance for this student/term
  const structure = db
    .prepare('SELECT amount FROM fee_structures WHERE class_id = ? AND term_id = ?')
    .get(payment.class_id, payment.term_id) as { amount: number } | undefined
  const paid = (
    db.prepare('SELECT COALESCE(SUM(amount),0) as s FROM fee_payments WHERE student_id = ? AND term_id = ?').get(
      payment.student_id,
      payment.term_id
    ) as { s: number }
  ).s
  const balance = structure ? Math.max(0, structure.amount - paid) : 0

  const doc = await PDFDocument.create()
  const page = doc.addPage([420, 595]) // A5 portrait
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)
  const { width, height } = page.getSize()
  const margin = 32
  const fmt = new Intl.NumberFormat('en').format

  const logo = await embedImageFile(doc, school?.logo_path ?? null)

  page.drawRectangle({ x: 0, y: height - 84, width, height: 84, color: rgb(0.96, 0.98, 0.97) })
  if (logo) {
    const d = logo.scaleToFit(48, 48)
    page.drawImage(logo, { x: margin, y: height - 68, width: d.width, height: d.height })
  }
  page.drawText((school?.name ?? 'School').toUpperCase(), { x: margin + 58, y: height - 40, size: 13, font: bold, color: BRAND })
  const addr = [school?.address, school?.phone].filter(Boolean).join(' · ')
  if (addr) page.drawText(addr, { x: margin + 58, y: height - 56, size: 8, font, color: MUTED })

  let y = height - 108
  page.drawText(T.receiptTitle, { x: margin, y, size: 14, font: bold, color: INK })
  page.drawText(`${T.receiptNo}: R-${String(payment.id).padStart(5, '0')}`, { x: width - margin - 130, y, size: 9, font, color: MUTED })
  y -= 14
  page.drawText(`${T.date}: ${new Date(payment.paid_at).toLocaleDateString()}`, { x: width - margin - 130, y, size: 9, font, color: MUTED })

  y -= 26
  const rows: [string, string][] = [
    [T.studentName, `${payment.first_name} ${payment.last_name}`],
    [T.admissionNo, payment.admission_no],
    [T.className, payment.class_name],
    [T.paymentMethod, METHOD_LABEL[payment.method] ?? payment.method],
    [T.reference, payment.reference ?? '-']
  ]
  for (const [label, value] of rows) {
    page.drawText(`${label}:`, { x: margin, y, size: 9, font, color: MUTED })
    page.drawText(value, { x: margin + 130, y, size: 10, font: bold, color: INK })
    y -= 22
  }

  y -= 6
  page.drawLine({ start: { x: margin, y }, end: { x: width - margin, y }, thickness: 0.5, color: LINE })
  y -= 26

  // Amount highlight
  page.drawRectangle({ x: margin, y: y - 40, width: width - margin * 2, height: 44, color: BRAND })
  page.drawText(T.amountPaid, { x: margin + 12, y: y - 16, size: 9, font, color: rgb(0.9, 0.95, 0.92) })
  page.drawText(`${fmt(payment.amount)} FCFA`, { x: margin + 12, y: y - 33, size: 16, font: bold, color: rgb(1, 1, 1) })
  y -= 60

  page.drawText(`${T.balance}: ${fmt(balance)} FCFA`, { x: margin, y, size: 11, font: bold, color: balance > 0 ? rgb(0.8, 0.3, 0.1) : BRAND })

  y -= 40
  page.drawText(`${T.received} — ${payment.recorded_by}`, { x: margin, y, size: 9, font, color: MUTED })

  page.drawText('Generated by JuniorIgnite', { x: margin, y: 24, size: 7, font, color: MUTED })

  const bytes = await doc.save()
  return savePdf(`receipt-${payment.admission_no}`, bytes)
}
